version: '3'
services:
  web:
    image: nginx
    volumes:
      - ./src/:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 80:80
    restart: always
    depends_on:
      - db
  db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_DB=DEFAULT_DB
      - POSTGRES_USER=DEFAULT_USER
      - POSTGRES_PASSWORD=DEFAULT_PASSWORD
    ports:
      - 5432:5432
